# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "/app"
tmp_dir = "/app/tmp"

[build]
    # Shell command to build the project
    poll = false
    cmd = "go build -o ./tmp/main ."
    # Binary file produced by `cmd`.
    bin = "./tmp/main"
    # Customize binary.
    full_bin = "./tmp/main"
    # Watch these filename extensions.
    include_ext = ["go", "tpl", "tmpl", "html"]
    # Ignore these filename extensions or directories.
    exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
    # Watch these directories if you specified.
    include_dir = []
    # Exclude specific files.
    exclude_file = []
    # Delay in milliseconds before triggering a build after a file change.
    delay = 1000
    # Stop running the old binary when build errors occur.
    stop_on_error = true
    # Log file location in your tmp_dir.
    log = "air_errors.log"

[log]
   # Show log time
   time = true
   level = "debug"

[color]
   # Customize each part's color. If no color found, use the raw app log.
   main = "magenta"
   watcher = "cyan"
   build = "yellow"
   runner = "green"

[misc]
   # Delete tmp directory on exit
   clean_on_exit = true

[run]
# Environment variables
env = ["APP_ENV=dev", "APP_USER=air"]